### ISSUE TITLE
Edit enrollment will unenroll a person

### ISSUE THREAD

**Issue by bramvandartel** [Inter-Actief/amelie#874] opened 2024-06-12 11:34 UTC
Tested on staging:
Edit the enrollment of a random person who is enrolled for an activity (e.g. change option) whilst there is a waiting list. Then, the message appears 'this person is already enrolled for this activity' and the person is unenrolled. The waiting list is not processed further (e.g. there are no people from the waiting list promoted to the final enrollments), until a new enrollment action occurs.

This seems to be a very weird bug only in case of a waiting list and only if a board member edits an enrollment.

**Comment by Kurocon** [comment] 2024-06-14 06:28
Duplicate of #829 ?

**Comment by supertom01** [comment] 2024-09-30 18:06
As Kevin indicates, this is a duplicate of #829

**Closed by supertom01** 2024-09-30 18:06 UTC
