### ISSUE TITLE
Reserve list for activities

### ISSUE THREAD

**Issue by WJ44** [Inter-Actief/amelie#585] opened 2021-11-02 14:19 UTC
Some other asssociations have the ability to sing up for a reserve list on the website when an activity is full. This would save a lot of administration and would also lower the barrier for members to put themselves on the reserve list.

**Comment by WKobes** [comment] 2021-11-02 14:24
Duplicate of #12 and #564

**Comment by WJ44** [comment] 2021-11-02 14:25
Hmm, apperently my search skills are not very good

**Closed by WKobes** 2021-11-02 14:24 UTC

**Comment by WKobes** [comment] 2021-11-02 14:26
Np, most likely you searched for open issues only! See the original issue for the discussion that have been held (and attempts that have been done)
