### ISSUE TITLE
Edit enrollment change

### ISSUE THREAD

**Issue by maasrf** [Inter-Actief/amelie#640] opened 2022-05-25 11:23 UTC
I like the possibility to edit the enrollment but I just tried and it deletes everything you have already filled in, which makes it a lot of work to make a small change (which it usually is) so I would like to have pre-filled in boxes with my previous answers so you only have to make the small change instead of having to fill everything out again

**Comment by WKobes** [comment] 2022-05-25 19:51
Duplicate of #630

**Closed by WKobes** 2022-05-25 19:51 UTC
Labels: enhancement
