### ISSUE TITLE
Free enrollment denied if direct debit mandate not signed

### ISSUE THREAD

**Issue by tnashk** [Inter-Actief/amelie#658] opened 2022-09-20 15:02 UTC
After clicking on 'enroll' button in enrollment form for an activity (https://www.inter-actief.utwente.nl/activities/6896/) with costs marked as 'free', I'm sent to a page with the message:
 "Unfortunately, you cannot enroll for this activity, because it has an entrance fee, and you have not signed a direct debit mandate for consumptions and activities..."

**Comment by Kurocon** [comment] 2022-09-22 11:20
Duplicate of https://github.com/Inter-Actief/amelie/issues/574

TLDR: This only occurs on activities with optional paid 'extras', and is very hard to fix in the current enrollment model. 

In this specific case, enrollment is not required for the new harvest drink but is only for dinner, so feel free to just show up without signing up!

**Closed by Kurocon** 2022-09-22 11:20 UTC
