### ISSUE TITLE
Enrollement options with limited availability

### ISSUE THREAD

**Issue by WJ44** [Inter-Actief/amelie#565] opened 2021-09-09 19:44 UTC
It would be nice to be able to add limited availability for enrollment options. This is perhaps mostly relevant due to corona related measures (limited physical and unlimited online for the same activity), but might come in handy now and then in normal situations as well.

**Comment by Kurocon** [comment] 2021-09-09 19:46
Duplicate of #517

**Closed** 2021-09-09 19:46 UTC
