### ISSUE TITLE
Internal Server Error when changing member profile picture

### ISSUE THREAD

**Issue by nielsedegroot** [Inter-Actief/amelie#412] opened 2018-09-27 19:28 UTC
Internal Server Error when changing member profile picture.

I tried to first delete the old image (of which I downloaded a back-up) and then add the new one but that didn't work either.

![image](https://user-images.githubusercontent.com/23638329/46169738-36825d00-c29c-11e8-887a-111c4e6dc325.png)

**Comment by Kurocon** [comment] 2021-01-25 20:18
Cannot reproduce, probably fixed in the mean time.

**Closed by Kurocon** 2021-01-25 20:18 UTC
Labels: bug
