### ISSUE TITLE
Opening Inter-Actief URLs through the app

### ISSUE THREAD

**Issue by Quitlox** [Inter-Actief/amelie#504] opened 2020-04-13 09:40 UTC
When opening a URL to e.g. activities or photo albums on mobile phone, it would be nice to be able to open it via the Inter-Actief app. People are usually still logged in on the app which makes enrolment easier, and besides that promotes app use.

- Jotte

**Comment by WKobes** [comment] 2020-04-30 23:03
Duplicate of #464

**Closed by WKobes** 2020-04-30 23:03 UTC
Labels: IA App, duplicate
