### ISSUE TITLE
Double filenames breaking photo uploads

### ISSUE THREAD

**Issue by CasEbbers** [Inter-Actief/amelie#247] opened 2017-05-22 08:09 UTC
When you upload photos to the same activity with the same filename (i.e. in multiple batches), something goes wrong in `Bijlage`, removing references to the thumbnails in the older upload. This results in an exception when `/activiteiten/xxxx/fotos/willekeurig/` is requested.

**Comment by WKobes** [comment] 2021-06-17 08:49
Duplicate of #549

**Closed by WKobes** 2021-06-17 08:49 UTC
Labels: back-end, bug
