### ISSUE TITLE
Make the preference for receiving IO/Vivat adjustable

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#392] opened 2018-07-11 15:24 UTC
Currently, the field for adjusting the preference to receive the IO/Vivat is only adjustable by the board. This should be adjustable by the person on their profile and during registration.

**Comment by SebastiaandenBoer** [comment] 2018-07-11 16:14
Ping #331

**Comment by Kurocon** [comment] 2018-07-11 19:00
Duplicate of #331

**Closed by Kurocon** 2018-07-11 19:00 UTC
Labels: Back-end, Front-end, Priority, easy-fix
