### ISSUE TITLE
Reserve list option on the site

### ISSUE THREAD

**Issue by bartleenheer** [Inter-Actief/amelie#564] opened 2021-09-09 11:18 UTC
As the title states, add a button on the website to add yourself to the reserve list on the website. This should make the process easier for keeping track of who's on the reserve list. This could even be extended so that the first person on the list gets enrolled automatically when someone unenrolls.

**Comment by WKobes** [comment] 2021-09-09 11:25
Duplicate of #12 

And has been attempted in the past, but this is really tricky. See the discussion in the original issue and PR.

**Closed by WKobes** 2021-09-09 11:25 UTC
