### ISSUE TITLE
Remove IA-staging from search engine results

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/amelie#659] opened 2022-10-09 20:39 UTC
Google (and potentially other) search engine have indexed [staging.inter-actief.utwente.nl](https://staging.ia.utwente.nl/).  Is it possible to have a separate `robots.txt` file for staging (and potentially development), blocking all search engines?

_Duplicate of old TRAC issue: [Beheer_Issues/13](https://github.com/Inter-Actief/Beheer_Issues/issues/13)_

**Comment by WKobes** [comment] 2022-10-09 20:40
Duplicate of #526

**Closed by WKobes** 2022-10-09 20:40 UTC
