### ISSUE TITLE
Sections on /committees page shift when hovering mouse

### ISSUE THREAD

**Issue by Jottee** [Inter-Actief/amelie#587] opened 2021-11-08 13:13 UTC
[Please write your issue in English]
When hovering your mouse e.g. vertically over the part of the https://www.inter-actief.utwente.nl/committees/ page the spacing and height between the sections keeps changing.

**Comment by Kurocon** [comment] 2023-09-18 11:03
Cannot reproduce, possibly fixed in the 2 years since this was opened.

**Closed by Kurocon** 2023-09-18 11:03 UTC
Labels: bug, front-end
