### ISSUE TITLE
Add education and external activities to the weekmail

### ISSUE THREAD

**Issue by 11gamer11** [Inter-Actief/amelie#184] opened 2017-01-09 11:51 UTC
It would be nice to chose education or external activities next to the normal activities to be added to the weekmail. (Including corresponding coloring in the template)

**Comment by windwarrior** [comment] 2017-01-09 15:54
Pointer: If I am not mistaken there is a superclass to all types of activities called "Event", you might be able to use this to abstract between the different activities.

**Comment by niomaster** [comment] 2017-02-20 14:29
Duplicate of #72

**Closed by niomaster** 2017-02-20 14:29 UTC
Labels: Back-end, duplicate, enhancement, Front-end, ready
