### ISSUE TITLE
Formatting m-number

### ISSUE THREAD

**Issue by Oliver-WD** [Inter-Actief/amelie#663] opened 2022-10-18 13:31 UTC
An employee who wants to be an Inter-_Actief_ member cannot sign up because his correct m-number isn't recognised. Can we see why the check fails and fix it?

**Comment by Kurocon** [comment] 2022-10-19 07:54
Duplicate of #546 - As Bram asked, please send us the M-number so we can debug as this is supposed to be an eleven-check the same as student numbers.

**Closed by Kurocon** 2022-10-19 07:54 UTC
