### ISSUE TITLE
Search function photo gallery broken

### ISSUE THREAD

**Issue by nielsedegroot** [Inter-Actief/amelie#311] opened 2018-01-31 11:05 UTC
When searching the photo gallery you get a results list with a few thumbnails which should be clickable to go to the album. These results are however currently not clickable so you have to go into the list and just click through pages and pages of photos.

**Comment by Kurocon** [comment] 2018-02-05 15:45
Duplicate of Inter-Actief/amelie#293

**Closed by Kurocon** 2018-02-05 15:45 UTC
