### ISSUE TITLE
Video upload throws 500 if an invalid video ID is given

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#451] opened 2019-03-08 12:14 UTC
On this line: https://github.com/Inter-Actief/amelie-private/blob/21e88bbebccb6825572637e1144d351d01f60219/amelie/tools/youtube.py#L14

The youtube retrieve_details function assumes that a video is always returned (it accesses the ```[0]``` element), but if an invalid video ID is given this list is empty and an IndexError is thrown. We should show a nice error message instead. In this case a part of a timestamp was accidentally included in the videoid (```7eutXL8fYZU&t```, note the ```&t``` at the end)

**Comment by WKobes** [comment] 2019-03-11 19:46
Duplicate of #435

**Closed by WKobes** 2019-03-11 19:46 UTC
