### ISSUE TITLE
Direct debit translation issue

### ISSUE THREAD

**Issue by Yoeori** [Inter-Actief/amelie#397] opened 2018-08-02 13:16 UTC
The email send to members for a direct debit contains a link to the direct debit which isn't translated yet: https://www.inter-actief.utwente.nl/streeplijst/incassoinstructie/xxxx/, which should be https://www.inter-actief.utwente.nl/personal_tab/debt_collection_instruction/xxxx/.

**Comment by WKobes** [comment] 2018-09-03 20:02
Duplicate of #402, which is fixed in a PR

**Closed by WKobes** 2018-09-03 20:02 UTC
