### ISSUE TITLE
Age is still incorrect

### ISSUE THREAD

**Issue by Nierot** [Inter-Actief/amelie#673] opened 2022-11-07 10:49 UTC
On birthdays, it shows the incorrect age for a person. This was seemingly fixed in #537 but at least for today is is not working.
Funnily enough, in the birthday mail is does show the correct age, while using the same method for calculating this number.

**Comment by Kurocon** [comment] 2022-11-07 10:50
Duplicate of https://github.com/Inter-Actief/amelie/issues/566

**Closed by Kurocon** 2022-11-07 10:50 UTC
