### ISSUE TITLE
Signing up external members

### ISSUE THREAD

**Issue by bartleenheer** [Inter-Actief/amelie#633] opened 2022-05-11 07:31 UTC
Currently, there is no actual way to sign up people that do not have an S-number. When trying to work around this limitation by filling in a random S-number, the OAuth mailing fails (#543), as the account isn't linked to a "user".

There are cases where signing up an external member would be nice, such as (board) members from sister associations. Creating a sign-up option where the S-number is optional should resolve this.

**Comment by WKobes** [comment] 2022-05-11 11:27
I'm gonna close this as a duplicate of #545. Indeed the work around with random s-numbers is not the way this should be done. Adding priority label to the other issue.

**Comment by WKobes** [comment] 2022-05-11 11:27
Duplicate of https://github.com/Inter-Actief/amelie/issues/545

**Closed by WKobes** 2022-05-11 11:27 UTC
