### ISSUE TITLE
Delete activity enrollment options data after the activity has been processed

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#393] opened 2018-07-11 15:34 UTC
Delete activity enrollment options data after the activity has been processed. 

Probably the best way to do this is to have a page where all activities that have not been anonymized are listed where board members can select activities that need to be anonymized. (Check if an activity is anonymized can be a simple boolean field in the activity).

Only enrollment options need to be removed or anonymized. Options which cost money cannot be deleted as it would change the personal tab balance, so for those the option itself needs to be anonymized to (Option 1, Option 2, etc.).

-description by Kevin-

**Comment by SebastiaandenBoer** [comment] 2018-07-11 16:13
Potential duplicate of #364

**Comment by Kurocon** [comment] 2018-07-11 19:00
Duplicate of #364

**Closed by Kurocon** 2018-07-11 19:00 UTC
Labels: Back-end, Front-end, Priority
